/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package phrasepass

import org.junit.jupiter.api.Test

class WordGeneratorTest {
    private val generator = WordGenerator()

    @Test
    fun testGenerateOneWord() {
        println(generator.nextWord())
    }

    @Test
    fun testGenerateNWords() {
        println(generator.getNWords(5))
    }
}
